  
services:
  loadbalancer:
    build: ./loadbalancer
    container_name: loadbalancer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net1
    privileged: true


  server:
    build: ./server
    image: ds-server  # This image name will now be available for the LB to use
    networks:
      - net1


networks:
  net1:
    driver: bridge
